import { Slide } from "./types"

export const Slides: Slide[] = [
  {
    id: 0,
    style: "modern",
    title: 'Современный (Modern)',
    description: '!Если цените порядок и функциональность. Идеально для жизни без лишних хлопот.',
    img: require('@/shared/assets/tinderLike/modern/modern_3.jpg'),
  },
  {
    id: 1,
    style: "scandinavian",
    title: 'Скандинавский',
    description: '!Если хотите уютную светлую квартиру даже в пасмурный день.',
    img: require('@/shared/assets/tinderLike/scandinavian/scandinavian_1.jpg'),
  },
  {
    id: 2,
    style: "loft",
    title: 'Лофт',
    description: 'Если мечтаете о брутальной студии, где можно всё, а кирпичная стена — лучший декор.',
    img: require('@/shared/assets/tinderLike/loft/loft_1.jpg'),
  },
  {
    id: 3,
    style: "classic",
    title: 'Классический',
    description: 'Если стремитесь к роскоши и респектабельности и готовы за ними ухаживать.',
    img: require('@/shared/assets/tinderLike/classic/classic_1.jpg'),
  },
  {
    id: 4,
    style: "min",
    title: 'Минимализм',
    description: 'Если не любите долго убирать пыль и верите, что пустота — это роскошь.',
    img: require('@/shared/assets/tinderLike/minimalism/min_1.jpg'),
  },
  {
    id: 5,
    style: "eco",
    title: 'Эко-стиль (Nature)',
    description: 'Если цените порядок и функциональность. Идеально для жизни без лишних хлопот.',
    img: require('@/shared/assets/tinderLike/ecoStyle/eco_1.jpg'),
  },
  {
    id: 6,
    style: "neo",
    title: 'Неоклассика (Modern Classic)',
    description: 'Если любите элегантность, но без музейной строгости. Золотая середина.',
    img: require('@/shared/assets/tinderLike/neoClassical/neo_1.jpg'),
  },
  {
    id: 7,
    style: "modern",
    title: 'Современный (Modern)',
    description: 'Когда каждый предмет на своём месте, а дизайн не отвлекает от жизни.',
    img: require('@/shared/assets/tinderLike/modern/modern_2.jpg'),
  },
  {
    id: 8,
    style: "scandinavian",
    title: 'Скандинавский',
    description: 'Чтобы создать ощущение летнего дня даже в декабре.',
    img: require('@/shared/assets/tinderLike/scandinavian/scandinavian_2.jpg'),
  },
  {
    id: 9,
    style: "loft",
    title: 'Лофт',
    description: ' Для тех, кто видит красоту в необработанном бетоне и открытых коммуникациях.',
    img: require('@/shared/assets/tinderLike/loft/loft_2.jpg'),
  },
  {
    id: 10,
    style: "classic",
    title: 'Классический',
    description: 'Для торжественных приёмов и атмосферы старой доброй солидности.',
    img: require('@/shared/assets/tinderLike/classic/classic_2.jpg'),
  },
  {
    id: 11,
    style: "min",
    title: 'Минимализм',
    description: 'Когда каждая новая вещь в доме — это осознанное и важное событие.',
    img: require('@/shared/assets/tinderLike/minimalism/min_2.jpg'),
  },
  {
    id: 12,
    style: "eco",
    title: 'Эко-стиль (Nature)',
    description: 'Чтобы не выходя из квартиры чувствовать связь с природой.',
    img: require('@/shared/assets/tinderLike/ecoStyle/eco_2.jpg'),
  },
  {
    id: 13,
    style: "neo",
    title: 'Неоклассика (Modern Classic)',
    description: 'Всё лучшее от классики, но для комфортной жизни в XXI веке.',
    img: require('@/shared/assets/tinderLike/neoClassical/neo_2.jpg'),
  },
  {
    id: 14,
    style: "modern",
    title: 'Современный (Modern)',
    description: 'Четкий план, встроенные шкафы и ничего лишнего. Максимум эффективности.',
    img: require('@/shared/assets/tinderLike/modern/modern_3.jpg'),
  },
  {
    id: 15,
    style: "scandinavian",
    title: 'Скандинавский',
    description: 'Много света, деревянные полы и уютный плед. Просто, тепло и по-домашнему.',
    img: require('@/shared/assets/tinderLike/scandinavian/scandinavian_3.jpg'),
  },
  {
    id: 16,
    style: "loft",
    title: 'Лофт',
    description: 'Пространство без перегородок, где кухня, гостиная и творческая мастерская — одно целое.',
    img: require('@/shared/assets/tinderLike/loft/loft_3.jpg'),
  },
  {
    id: 17,
    style: "classic",
    title: 'Классический',
    description: 'Для тех, кто верит, что лепнина, паркет и хрустальная люстра — это навсегда.',
    img: require('@/shared/assets/tinderLike/classic/classic_3.jpg'),
  },
  {
    id: 18,
    style: "min",
    title: 'Минимализм',
    description: 'Философия чистых поверхностей. Где каждая деталь выверена, а беспорядку просто негде спрятаться.',
    img: require('@/shared/assets/tinderLike/minimalism/min_3.jpg'),
  },
  {
    id: 19,
    style: "eco",
    title: 'Эко-стиль (Nature)',
    description: 'Дом как продолжение леса или сада. Натуральные текстуры, живые растения и покой.',
    img: require('@/shared/assets/tinderLike/ecoStyle/eco_3.jpg'),
  },
  {
    id: 20,
    style: "neo",
    title: 'Неоклассика (Modern Classic)',
    description: 'Элегантная лепнина соседствует с современной техникой. Традиции без тяжеловесности.',
    img: require('@/shared/assets/tinderLike/neoClassical/neo_3.jpg'),
  },
  {
    id: 21,
    style: "modern",
    title: 'Современный (Modern)',
    description: 'Интерьер как удобный инструмент для жизни. Никакой лишней сложности.',
    img: require('@/shared/assets/tinderLike/modern/modern_4.jpg'),
  },
  {
    id: 22,
    style: "scandinavian",
    title: 'Скандинавский',
    description: 'Как чашка горячего кофе у окна в зимнее утро. Уютно, светло и без суеты.',
    img: require('@/shared/assets/tinderLike/scandinavian/scandinavian_4.jpg'),
  },
  {
    id: 23,
    style: "loft",
    title: 'Лофт',
    description: 'Свобода самовыражения. Можно оставить кирпичную кладку и не прятать трубы.',
    img: require('@/shared/assets/tinderLike/loft/loft_4.jpg'),
  },
  {
    id: 24,
    style: "classic",
    title: 'Классический',
    description: 'Для вечеров в кресле у камина (или его имитации). Атмосфера наследия и достатка.',
    img: require('@/shared/assets/tinderLike/classic/classic_4.jpg'),
  },
  {
    id: 25,
    style: "min",
    title: 'Минимализм',
    description: 'Искусство оставлять самое главное. Воздух и покой — ваши главные украшения.',
    img: require('@/shared/assets/tinderLike/minimalism/min_4.jpg'),
  },
  {
    id: 26,
    style: "eco",
    title: 'Эко-стиль (Nature)',
    description: 'Шум города остаётся за дверью. Внутри — запах дерева, шепот листьев и спокойствие.',
    img: require('@/shared/assets/tinderLike/ecoStyle/eco_4.png'),
  },
  {
    id: 27,
    style: "neo",
    title: 'Неоклассика (Modern Classic)',
    description: 'Красота, проверенная веками, но без строгих правил. Элегантность, в которой можно расслабиться.',
    img: require('@/shared/assets/tinderLike/neoClassical/neo_4.jpg'),
  },

  
]